# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Any

type Query {
  meetings: [Meeting]!
  sessions(meeting_keys: [Int]!): [Session]!
  drivers(session_key: Int!): [Driver]!
  positions(session_key: Int!): [Position]!
  raceControls(session_key: Int!): [RaceControl]!
  laps(session_key: Int!): [Lap]!
  intervals(session_key: Int!): [Interval]!
}

type Subscription {
  lapTimes: [LapTime]!
  positions: [Position]!
  carData: CarData!
}

type Session {
  session_key: Int!
  session_name: String!
  date_start: String!
  date_end: String!
  gmt_offset: String!
  session_type: String!
  meeting_key: Int!
}

type Meeting {
  meeting_name: String!
  meeting_official_name: String!
  location: String!
  country_code: String!
  country_name: String!
  circuit_short_name: String!
  meeting_key: Int!
}

type Driver {
  session_key:   Int!
  broadcast_name: String!
  country_code:   String!
  first_name: String!
  full_name: String!
  headshot_url:   String!
  last_name:      String!
  racing_number: Int!
  team_colour: String
  team_name: String
  abbreviation: String
}

type Position {
  session_key: Int!
  racing_number: Int!
  position: Int!
}

type RaceControl {
  session_key: Int!
  meeting_key: Int!
  date: String!
  category: String
  flag: String
  lap_number: Int
  message: String
  racing_number: Int
  scope: String
  sector: Int
}

type Lap {
  meeting_key: Int!
  session_key: Int!
  racing_number: Int!
  i1_speed: Int
  i2_speed: Int
  st_speed: Int
  date_start: String!
  lap_duration: Float
  is_pit_out_lap: Boolean!
  duration_sector_1: Float
  duration_sector_2: Float
  duration_sector_3: Float
  segments_sector_1: [Int]
  segments_sector_2: [Int]
  segments_sector_3: [Int]
  lap_number: Int!
}

type LapTime {
  session_key: Int!
  racing_number: String!
  number_of_laps: Int!
  best_lap_time: Any
  last_lap_time: Any
  gap_to_leader: String
  interval_to_position_ahead: Any
}

type Interval {
  date:  String!
  racing_number: Int!
  meeting_key: Int!
  session_key: Int!
  gap_to_leader:  Any
  interval: Any
}

type CarData {
  compressed: String!
}