package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	dataingestor "F1Telemetry-new-server/data-ingestor"
	"F1Telemetry-new-server/graph/model"
	"context"
)

var ctx = context.Background()
var dbClient, err = dataingestor.GetMongoClient(&ctx)

// Meetings is the resolver for the meetings field.
func (r *queryResolver) Meetings(ctx context.Context) ([]*model.Meeting, error) {
	if err != nil {
		return nil, err
	}
	meetings, err := dataingestor.FetchMeetings(dbClient, ctx)
	if err != nil {
		return nil, err
	}
	var meetingsInt []*model.Meeting
	for _, meeting := range meetings {
		meetingsInt = append(meetingsInt, &meeting)
	}
	return meetingsInt, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, meetingKeys []*int) ([]*model.Session, error) {
	if err != nil {
		return nil, err
	}
	var sessionsInt []*model.Session
	for _, meetingKey := range meetingKeys {
		sessions, err := dataingestor.FetchSessions(dbClient, ctx, *meetingKey)
		if err != nil {
			return nil, err
		}
		for _, session := range sessions {
			sessionsInt = append(sessionsInt, &session)
		}
	}
	return sessionsInt, nil
}

// Drivers is the resolver for the drivers field.
func (r *queryResolver) Drivers(ctx context.Context, sessionKey int) ([]*model.Driver, error) {
	if err != nil {
		return nil, err
	}
	drivers, err := dataingestor.FetchDrivers(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var driversInt []*model.Driver
	for _, driver := range drivers {
		driversInt = append(driversInt, &driver)
	}
	return driversInt, nil
}

// Positions is the resolver for the positions field.
func (r *queryResolver) Positions(ctx context.Context, sessionKey int) ([]*model.Position, error) {
	if err != nil {
		return nil, err
	}
	positions, err := dataingestor.FetchPositions(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var positionsInt []*model.Position
	for _, position := range positions {
		positionsInt = append(positionsInt, &position)
	}
	return positionsInt, nil
}

// RaceControl is the resolver for the raceControl field.
func (r *queryResolver) RaceControl(ctx context.Context, sessionKey int) ([]*model.RaceControl, error) {
	if err != nil {
		return nil, err
	}
	raceControl, err := dataingestor.FetchRaceControl(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var raceControlInt []*model.RaceControl
	for _, raceControlMessage := range raceControl {
		raceControlInt = append(raceControlInt, &raceControlMessage)
	}
	return raceControlInt, nil
}

// LapTimes is the resolver for the lapTimes field.
func (r *queryResolver) LapTimes(ctx context.Context, sessionKey int) ([]*model.Timing, error) {
	if err != nil {
		return nil, err
	}
	timings, err := dataingestor.FetchTimings(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var timingsInt []*model.Timing
	for _, timing := range timings {
		timingsInt = append(timingsInt, &timing)
	}
	return timingsInt, nil
}

// Sectors is the resolver for the sectors field.
func (r *queryResolver) Sectors(ctx context.Context, sessionKey int) ([]*model.Sector, error) {
	if err != nil {
		return nil, err
	}
	sectors, err := dataingestor.FetchSectors(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var sectorsInt []*model.Sector
	for _, sector := range sectors {
		sectorsInt = append(sectorsInt, &sector)
	}
	return sectorsInt, nil
}

// Stints is the resolver for the stints field.
func (r *queryResolver) Stints(ctx context.Context, sessionKey int) ([]*model.Stint, error) {
	if err != nil {
		return nil, err
	}
	stints, err := dataingestor.FetchStints(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var stintsInt []*model.Stint
	for _, stint := range stints {
		stintsInt = append(stintsInt, &stint)
	}
	return stintsInt, nil
}

// LapTimes is the resolver for the lapTimes field.
func (r *subscriptionResolver) LapTimes(ctx context.Context) (<-chan []*model.LapTime, error) {
	id := dataingestor.GenerateRandomString(8)
	lapTimes := make(chan []*model.LapTime, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.LapTimeObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.LapTimeObservers[id] = lapTimes
	r.mu.Unlock()
	r.LapTimeObservers[id] <- r.CurrentLapTimes
	return lapTimes, nil
}

// Positions is the resolver for the positions field.
func (r *subscriptionResolver) Positions(ctx context.Context) (<-chan []*model.Position, error) {
	id := dataingestor.GenerateRandomString(8)
	positions := make(chan []*model.Position, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.PositionObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.PositionObservers[id] = positions
	r.mu.Unlock()
	r.PositionObservers[id] <- r.CurrentPositions
	return positions, nil
}

// CarData is the resolver for the carData field.
func (r *subscriptionResolver) CarData(ctx context.Context) (<-chan *model.CarData, error) {
	id := dataingestor.GenerateRandomString(8)
	carData := make(chan *model.CarData, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.CarDataObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.CarDataObservers[id] = carData
	r.mu.Unlock()
	r.CarDataObservers[id] <- r.CurrentCarData
	return carData, nil
}

// RaceControl is the resolver for the raceControl field.
func (r *subscriptionResolver) RaceControl(ctx context.Context) (<-chan []*model.RaceControl, error) {
	id := dataingestor.GenerateRandomString(8)
	raceControl := make(chan []*model.RaceControl, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.RaceControlObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.RaceControlObservers[id] = raceControl
	r.mu.Unlock()
	r.RaceControlObservers[id] <- r.CurrentRaceControlMessages
	return raceControl, nil
}

// Stints is the resolver for the stints field.
func (r *subscriptionResolver) Stints(ctx context.Context) (<-chan []*model.Stint, error) {
	id := dataingestor.GenerateRandomString(8)
	stints := make(chan []*model.Stint, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.StintObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.StintObservers[id] = stints
	r.mu.Unlock()
	r.StintObservers[id] <- r.CurrentStints
	return stints, nil
}

// Sectors is the resolver for the sectors field.
func (r *subscriptionResolver) Sectors(ctx context.Context) (<-chan []*model.Sector, error) {
	id := dataingestor.GenerateRandomString(8)
	sectors := make(chan []*model.Sector, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.SectorTimeObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.SectorTimeObservers[id] = sectors
	r.mu.Unlock()
	r.SectorTimeObservers[id] <- r.CurrentSectorTimes
	return sectors, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	var ctx = context.Background()
var dbClient, err = dataingestor.GetMongoClient(&ctx)
*/
