# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Any

type Query {
  meetings: [Meeting]!
  sessions(meeting_keys: [Int]!): [Session]!
  drivers(session_key: Int!): [Driver]!
  positions(session_key: Int!): [Position]!
}

type Subscription {
  lapTimes: [LapTime]!
  positions: [Position]!
  carData: CarData!
  raceControl: [RaceControl]!
  stints: [Stint]!
  sectors: [Sector]!
}

type Session {
  session_key: Int!
  session_name: String!
  date_start: String!
  date_end: String!
  gmt_offset: String!
  session_type: String!
  meeting_key: Int!
}

type Meeting {
  meeting_name: String!
  meeting_official_name: String!
  location: String!
  country_code: String!
  country_name: String!
  circuit_short_name: String!
  meeting_key: Int!
}

type Driver {
  session_key:   Int!
  broadcast_name: String!
  country_code:   String!
  first_name: String!
  full_name: String!
  headshot_url:   String!
  last_name:      String!
  racing_number: Int!
  team_colour: String
  team_name: String
  abbreviation: String
}

type Position {
  session_key: Int!
  racing_number: Int!
  position: Int!
}

type RaceControl {
  date: String!
  category: String
  flag: String
  lap_number: Int
  message: String!
  scope: String
}

type Lap {
  meeting_key: Int!
  session_key: Int!
  racing_number: Int!
  i1_speed: Int
  i2_speed: Int
  st_speed: Int
  date_start: String!
  lap_duration: Float
  is_pit_out_lap: Boolean!
  duration_sector_1: Float
  duration_sector_2: Float
  duration_sector_3: Float
  segments_sector_1: [Int]
  segments_sector_2: [Int]
  segments_sector_3: [Int]
  lap_number: Int!
}

type LapTime {
  session_key: Int!
  racing_number: String!
  number_of_laps: Int!
  best_lap_time: Any
  last_lap_time: Time!
  gap_to_leader: String
  interval_to_position_ahead: Any
}

type Time {
  value: String!
  overallFastest: Boolean!
  personalFastest: Boolean!
}

type CarData {
  compressed: String!
}

type Stint {
  racing_number:     Int! 
	lap_flags:         Int!   
	compound:          String!
	new:               Boolean!  
	tyres_not_changed: Int! 
	total_laps:        Int!    
	start_laps:        Int!  
	timestamp:         String!
	stint_number:      Int! 
}

type Sector {
  racing_number: Int!
  sector_number: Int!
  value: String!
  overall_fastest: Boolean!
  personal_fastest: Boolean!
  utc: String
}