package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	dataingestor "F1Telemetry-new-server/data-ingestor"
	"F1Telemetry-new-server/graph/model"
	"context"
)

// Meetings is the resolver for the meetings field.
func (r *queryResolver) Meetings(ctx context.Context) ([]*model.Meeting, error) {
	meetings, err := dataingestor.FetchMeetings(dbClient, ctx)
	if err != nil {
		return nil, err
	}
	var meetingsInt []*model.Meeting
	for _, meeting := range meetings {
		meetingsInt = append(meetingsInt, &meeting)
	}
	return meetingsInt, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, meetingKeys []*int) ([]*model.Session, error) {
	var sessionsInt []*model.Session
	for _, meetingKey := range meetingKeys {
		sessions, err := dataingestor.FetchSessions(dbClient, ctx, *meetingKey)
		if err != nil {
			return nil, err
		}
		for _, session := range sessions {
			sessionsInt = append(sessionsInt, &session)
		}
	}
	return sessionsInt, nil
}

// Drivers is the resolver for the drivers field.
func (r *queryResolver) Drivers(ctx context.Context, sessionKey int) ([]*model.Driver, error) {
	drivers, err := dataingestor.FetchDrivers(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var driversInt []*model.Driver
	for _, driver := range drivers {
		driversInt = append(driversInt, &driver)
	}
	return driversInt, nil
}

// Positions is the resolver for the positions field.
func (r *queryResolver) Positions(ctx context.Context, sessionKey int) ([]*model.Position, error) {
	positions, err := dataingestor.FetchPositions(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var positionsInt []*model.Position
	for _, position := range positions {
		positionsInt = append(positionsInt, &position)
	}
	return positionsInt, nil
}

// RaceControl is the resolver for the raceControl field.
func (r *queryResolver) RaceControl(ctx context.Context, sessionKey int) ([]*model.RaceControl, error) {
	raceControl, err := dataingestor.FetchRaceControl(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var raceControlInt []*model.RaceControl
	for _, raceControlMessage := range raceControl {
		raceControlInt = append(raceControlInt, &raceControlMessage)
	}
	return raceControlInt, nil
}

// LapTimes is the resolver for the lapTimes field.
func (r *queryResolver) LapTimes(ctx context.Context, sessionKey int) ([]*model.Timing, error) {
	timings, err := dataingestor.FetchTimings(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var timingsInt []*model.Timing
	for _, timing := range timings {
		timingsInt = append(timingsInt, &timing)
	}
	return timingsInt, nil
}

// Sectors is the resolver for the sectors field.
func (r *queryResolver) Sectors(ctx context.Context, sessionKey int) ([]*model.Sector, error) {
	sectors, err := dataingestor.FetchSectors(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var sectorsInt []*model.Sector
	for _, sector := range sectors {
		sectorsInt = append(sectorsInt, &sector)
	}
	return sectorsInt, nil
}

// Stints is the resolver for the stints field.
func (r *queryResolver) Stints(ctx context.Context, sessionKey int) ([]*model.Stint, error) {
	stints, err := dataingestor.FetchStints(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var stintsInt []*model.Stint
	for _, stint := range stints {
		stintsInt = append(stintsInt, &stint)
	}
	return stintsInt, nil
}

// TrackStatus is the resolver for the trackStatus field.
func (r *queryResolver) TrackStatus(ctx context.Context, sessionKey int) ([]*model.TrackStatus, error) {
	trackStatus, err := dataingestor.FetchTrackStatus(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var trackStatusInt []*model.TrackStatus
	for _, status := range trackStatus {
		trackStatusInt = append(trackStatusInt, &status)
	}
	return trackStatusInt, nil
}

// Weather is the resolver for the weather field.
func (r *queryResolver) Weather(ctx context.Context, sessionKey int) ([]*model.Weather, error) {
	weather, err := dataingestor.FetchWeather(dbClient, ctx, sessionKey)
	if err != nil {
		return nil, err
	}
	var weatherInt []*model.Weather
	for _, w := range weather {
		weatherInt = append(weatherInt, &w)
	}
	return weatherInt, nil
}

// SegmentCounts is the resolver for the segmentCounts field.
func (r *queryResolver) SegmentCounts(ctx context.Context) (*model.SegmentCounts, error) {
	counts := r.GetSegmentCounts()
	if counts == [3]int{} {
		return nil, nil
	}
	return &model.SegmentCounts{
		Sector1: counts[0],
		Sector2: counts[1],
		Sector3: counts[2],
	}, nil
}

// LapTimes is the resolver for the lapTimes subscription field.
func (r *subscriptionResolver) LapTimes(ctx context.Context) (<-chan []*model.LapTime, error) {
	id := dataingestor.GenerateRandomString(8)
	lapTimes := make(chan []*model.LapTime, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.LapTimeObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.LapTimeObservers[id] = lapTimes
	lapTimes <- r.CurrentLapTimes
	r.mu.Unlock()
	return lapTimes, nil
}

// Positions is the resolver for the positions subscription field.
func (r *subscriptionResolver) Positions(ctx context.Context) (<-chan []*model.Position, error) {
	id := dataingestor.GenerateRandomString(8)
	positions := make(chan []*model.Position, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.PositionObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.PositionObservers[id] = positions
	positions <- r.CurrentPositions
	r.mu.Unlock()
	return positions, nil
}

// CarData is the resolver for the carData subscription field.
func (r *subscriptionResolver) CarData(ctx context.Context) (<-chan *model.CarData, error) {
	id := dataingestor.GenerateRandomString(8)
	carData := make(chan *model.CarData, 64)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.CarDataObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.CarDataObservers[id] = carData
	if r.CurrentCarData != nil {
		select {
		case carData <- r.CurrentCarData:
		default:
		}
	}
	r.mu.Unlock()
	return carData, nil
}

// RaceControl is the resolver for the raceControl subscription field.
func (r *subscriptionResolver) RaceControl(ctx context.Context) (<-chan []*model.RaceControl, error) {
	id := dataingestor.GenerateRandomString(8)
	raceControl := make(chan []*model.RaceControl, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.RaceControlObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.RaceControlObservers[id] = raceControl
	raceControl <- r.CurrentRaceControlMessages
	r.mu.Unlock()
	return raceControl, nil
}

// Stints is the resolver for the stints subscription field.
func (r *subscriptionResolver) Stints(ctx context.Context) (<-chan []*model.Stint, error) {
	id := dataingestor.GenerateRandomString(8)
	stints := make(chan []*model.Stint, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.StintObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.StintObservers[id] = stints
	stints <- r.CurrentStints
	r.mu.Unlock()
	return stints, nil
}

// Sectors is the resolver for the sectors subscription field.
func (r *subscriptionResolver) Sectors(ctx context.Context) (<-chan []*model.Sector, error) {
	id := dataingestor.GenerateRandomString(8)
	sectors := make(chan []*model.Sector, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.SectorTimeObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.SectorTimeObservers[id] = sectors
	sectors <- r.CurrentSectorTimes
	r.mu.Unlock()
	return sectors, nil
}

// Segments is the resolver for the segments subscription field.
func (r *subscriptionResolver) Segments(ctx context.Context) (<-chan []*model.Segment, error) {
	id := dataingestor.GenerateRandomString(8)
	segments := make(chan []*model.Segment, 1)
	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.SegmentObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.SegmentObservers[id] = segments
	if r.CurrentSegments != nil {
		segments <- r.CurrentSegments
	}
	r.mu.Unlock()
	return segments, nil
}

// TrackStatus is the resolver for the trackStatus subscription field.
func (r *subscriptionResolver) TrackStatus(ctx context.Context) (<-chan []*model.TrackStatus, error) {
	id := dataingestor.GenerateRandomString(8)
	trackStatus := make(chan []*model.TrackStatus, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.TrackStatusObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.TrackStatusObservers[id] = trackStatus
	trackStatus <- r.CurrentTrackStatus
	r.mu.Unlock()
	return trackStatus, nil
}

// Weather is the resolver for the weather subscription field.
func (r *subscriptionResolver) Weather(ctx context.Context) (<-chan *model.Weather, error) {
	id := dataingestor.GenerateRandomString(8)
	weather := make(chan *model.Weather, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.WeatherObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.WeatherObservers[id] = weather
	if r.CurrentWeather != nil {
		weather <- r.CurrentWeather
	}
	r.mu.Unlock()
	return weather, nil
}

// DriverLocations is the resolver for the driverLocations subscription field.
func (r *subscriptionResolver) DriverLocations(ctx context.Context) (<-chan []*model.DriverPosition, error) {
	id := dataingestor.GenerateRandomString(8)
	driverLocations := make(chan []*model.DriverPosition, 64)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.DriverLocationObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.DriverLocationObservers[id] = driverLocations
	if r.CurrentDriverLocations != nil {
		select {
		case driverLocations <- r.CurrentDriverLocations:
		default:
		}
	}
	r.mu.Unlock()
	return driverLocations, nil
}

// QualifyingData is the resolver for the qualifyingData field.
func (r *subscriptionResolver) QualifyingData(ctx context.Context) (<-chan *model.QualifyingData, error) {
	id := dataingestor.GenerateRandomString(8)
	qualifyingData := make(chan *model.QualifyingData, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.QualifyingDataObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.QualifyingDataObservers[id] = qualifyingData
	if r.CurrentQualifyingData != nil {
		select {
		case qualifyingData <- r.CurrentQualifyingData:
		default:
		}
	}
	r.mu.Unlock()
	return qualifyingData, nil
}

// LapCount is the resolver for the lapCount subscription field.
func (r *subscriptionResolver) LapCount(ctx context.Context) (<-chan *model.LapCount, error) {
	id := dataingestor.GenerateRandomString(8)
	lapCount := make(chan *model.LapCount, 1)

	go func() {
		<-ctx.Done()
		r.mu.Lock()
		delete(r.LapCountObservers, id)
		r.mu.Unlock()
	}()
	r.mu.Lock()
	r.LapCountObservers[id] = lapCount
	if r.CurrentLapCount != nil {
		select {
		case lapCount <- r.CurrentLapCount:
		default:
		}
	}
	r.mu.Unlock()
	return lapCount, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
