package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	dataingestor "F1Telemetry-new-server/data-ingestor"
	"F1Telemetry-new-server/graph/model"
	"context"
)

var ctx = context.Background()
var dbClient, err = dataingestor.GetMongoClient(&ctx)

// Meetings is the resolver for the meetings field.
func (r *queryResolver) Meetings(ctx context.Context) ([]*model.Meeting, error) {
	if err != nil {
		return nil, err
	}
	meetings, err := dataingestor.FetchMeetings(dbClient, ctx)
	if err != nil {
		return nil, err
	}
	var meetingsInt []*model.Meeting
	for _, meeting := range meetings {
		meetingsInt = append(meetingsInt, &meeting)
	}
	return meetingsInt, nil
}

// Sessions is the resolver for the sessions field.
func (r *queryResolver) Sessions(ctx context.Context, meetingKeys []*int) ([]*model.Session, error) {
	if err != nil {
		return nil, err
	}
	var sessionsInt []*model.Session
	for _, meetingKey := range meetingKeys {
		sessions, err := dataingestor.FetchSessions(dbClient, ctx, *meetingKey)
		if err != nil {
			return nil, err
		}
		for _, session := range sessions {
			sessionsInt = append(sessionsInt, &session)
		}
	}
	return sessionsInt, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	var ctx = context.Background()
var dbClient, err = dataingestor.GetMongoClient(&ctx)
*/
