// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/bsontype"
	"strconv"
)

type GapToLeader struct {
	Value interface{}
}

func (g *GapToLeader) UnmarshalBSONValue(t bsontype.Type, data []byte) error {
	var err error
	switch t {
	case bson.TypeDouble:
		var floatValue float64
		fmt.Printf("floatValue: %v\n", floatValue)
		err = bson.Unmarshal(data, &floatValue)
		fmt.Printf("error: %v\n", err)
		g.Value = floatValue
	case bson.TypeString:
		var stringValue string
		err = bson.Unmarshal(data, &stringValue)
		fmt.Printf("error: %v\n", err)
		g.Value = stringValue
	default:
		fmt.Printf("unexpected BSON type %v\n", t)
		//err = fmt.Errorf("unexpected BSON type %v", t)
	}
	return nil
}

func (g GapToLeader) String() string {
	switch v := g.Value.(type) {
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	case string:
		return v
	default:
		return ""
	}
}

type CarData struct {
	Brake        int    `json:"brake"`
	Date         string `json:"date"`
	DriverNumber int    `json:"driver_number"`
	Drs          int    `json:"drs"`
	MeetingKey   int    `json:"meeting_key"`
	NGear        int    `json:"n_gear"`
	Rpm          int    `json:"rpm"`
	SessionKey   int    `json:"session_key"`
	Speed        int    `json:"speed"`
	Throttle     int    `json:"throttle"`
}

type Driver struct {
	SessionKey    int     `json:"session_key"`
	MeetingKey    int     `json:"meeting_key"`
	BroadcastName string  `json:"broadcast_name"`
	CountryCode   string  `json:"country_code"`
	FirstName     string  `json:"first_name"`
	FullName      string  `json:"full_name"`
	HeadshotURL   string  `json:"headshot_url"`
	LastName      string  `json:"last_name"`
	DriverNumber  int     `json:"driver_number"`
	TeamColour    *string `json:"team_colour,omitempty"`
	TeamName      *string `json:"team_name,omitempty"`
	NameAcronym   *string `json:"name_acronym,omitempty"`
}

type Interval struct {
	Date         string      `json:"date"`
	DriverNumber int         `json:"driver_number"`
	MeetingKey   int         `json:"meeting_key"`
	SessionKey   int         `json:"session_key"`
	GapToLeader  GapToLeader `bson:"gaptoleader"`
	Interval     GapToLeader `bson:"interval"`
}

type Lap struct {
	MeetingKey      int      `json:"meeting_key"`
	SessionKey      int      `json:"session_key"`
	DriverNumber    int      `json:"driver_number"`
	I1Speed         *int     `json:"i1_speed,omitempty"`
	I2Speed         *int     `json:"i2_speed,omitempty"`
	StSpeed         *int     `json:"st_speed,omitempty"`
	DateStart       string   `json:"date_start"`
	LapDuration     *float64 `json:"lap_duration,omitempty"`
	IsPitOutLap     bool     `json:"is_pit_out_lap"`
	DurationSector1 *float64 `json:"duration_sector_1,omitempty"`
	DurationSector2 *float64 `json:"duration_sector_2,omitempty"`
	DurationSector3 *float64 `json:"duration_sector_3,omitempty"`
	SegmentsSector1 []*int   `json:"segments_sector_1,omitempty"`
	SegmentsSector2 []*int   `json:"segments_sector_2,omitempty"`
	SegmentsSector3 []*int   `json:"segments_sector_3,omitempty"`
	LapNumber       int      `json:"lap_number"`
}

type Meeting struct {
	MeetingName         string `json:"meeting_name"`
	MeetingOfficialName string `json:"meeting_official_name"`
	Location            string `json:"location"`
	CountryKey          int    `json:"country_key"`
	CountryCode         string `json:"country_code"`
	CountryName         string `json:"country_name"`
	CircuitKey          int    `json:"circuit_key"`
	CircuitShortName    string `json:"circuit_short_name"`
	DateStart           string `json:"date_start"`
	GmtOffset           string `json:"gmt_offset"`
	MeetingKey          int    `json:"meeting_key"`
	Year                int    `json:"year"`
}

type Position struct {
	SessionKey   int    `json:"session_key"`
	MeetingKey   int    `json:"meeting_key"`
	DriverNumber int    `json:"driver_number"`
	Date         string `json:"date"`
	Position     int    `json:"position"`
}

type Query struct {
}

type RaceControl struct {
	SessionKey   int     `json:"session_key"`
	MeetingKey   int     `json:"meeting_key"`
	Date         string  `json:"date"`
	Category     *string `json:"category,omitempty"`
	Flag         *string `json:"flag,omitempty"`
	LapNumber    *int    `json:"lap_number,omitempty"`
	Message      *string `json:"message,omitempty"`
	DriverNumber *int    `json:"driver_number,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	Sector       *int    `json:"sector,omitempty"`
}

type Session struct {
	SessionKey       int    `json:"session_key"`
	SessionName      string `json:"session_name"`
	DateStart        string `json:"date_start"`
	DateEnd          string `json:"date_end"`
	GmtOffset        string `json:"gmt_offset"`
	SessionType      string `json:"session_type"`
	MeetingKey       int    `json:"meeting_key"`
	Location         string `json:"location"`
	CountryKey       int    `json:"country_key"`
	CountryCode      string `json:"country_code"`
	CountryName      string `json:"country_name"`
	CircuitKey       int    `json:"circuit_key"`
	CircuitShortName string `json:"circuit_short_name"`
	Year             int    `json:"year"`
}
