// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CarData struct {
	Compressed string `json:"compressed"`
}

type Driver struct {
	SessionKey    int     `json:"session_key"`
	BroadcastName string  `json:"broadcast_name"`
	CountryCode   string  `json:"country_code"`
	FirstName     string  `json:"first_name"`
	FullName      string  `json:"full_name"`
	HeadshotURL   string  `json:"headshot_url"`
	LastName      string  `json:"last_name"`
	RacingNumber  int     `json:"racing_number"`
	TeamColour    *string `json:"team_colour,omitempty"`
	TeamName      *string `json:"team_name,omitempty"`
	Abbreviation  *string `json:"abbreviation,omitempty"`
}

type Interval struct {
	Date         string `json:"date"`
	RacingNumber int    `json:"racing_number"`
	MeetingKey   int    `json:"meeting_key"`
	SessionKey   int    `json:"session_key"`
	GapToLeader  any    `json:"gap_to_leader,omitempty"`
	Interval     any    `json:"interval,omitempty"`
}

type Lap struct {
	MeetingKey      int      `json:"meeting_key"`
	SessionKey      int      `json:"session_key"`
	RacingNumber    int      `json:"racing_number"`
	I1Speed         *int     `json:"i1_speed,omitempty"`
	I2Speed         *int     `json:"i2_speed,omitempty"`
	StSpeed         *int     `json:"st_speed,omitempty"`
	DateStart       string   `json:"date_start"`
	LapDuration     *float64 `json:"lap_duration,omitempty"`
	IsPitOutLap     bool     `json:"is_pit_out_lap"`
	DurationSector1 *float64 `json:"duration_sector_1,omitempty"`
	DurationSector2 *float64 `json:"duration_sector_2,omitempty"`
	DurationSector3 *float64 `json:"duration_sector_3,omitempty"`
	SegmentsSector1 []*int   `json:"segments_sector_1,omitempty"`
	SegmentsSector2 []*int   `json:"segments_sector_2,omitempty"`
	SegmentsSector3 []*int   `json:"segments_sector_3,omitempty"`
	LapNumber       int      `json:"lap_number"`
}

type LapTime struct {
	SessionKey              int     `json:"session_key"`
	RacingNumber            string  `json:"racing_number"`
	NumberOfLaps            int     `json:"number_of_laps"`
	BestLapTime             any     `json:"best_lap_time,omitempty"`
	LastLapTime             any     `json:"last_lap_time,omitempty"`
	GapToLeader             *string `json:"gap_to_leader,omitempty"`
	IntervalToPositionAhead any     `json:"interval_to_position_ahead,omitempty"`
}

type Meeting struct {
	MeetingName         string `json:"meeting_name"`
	MeetingOfficialName string `json:"meeting_official_name"`
	Location            string `json:"location"`
	CountryCode         string `json:"country_code"`
	CountryName         string `json:"country_name"`
	CircuitShortName    string `json:"circuit_short_name"`
	MeetingKey          int    `json:"meeting_key"`
}

type Position struct {
	SessionKey   int `json:"session_key"`
	RacingNumber int `json:"racing_number"`
	Position     int `json:"position"`
}

type Query struct {
}

type RaceControl struct {
	SessionKey   int     `json:"session_key"`
	MeetingKey   int     `json:"meeting_key"`
	Date         string  `json:"date"`
	Category     *string `json:"category,omitempty"`
	Flag         *string `json:"flag,omitempty"`
	LapNumber    *int    `json:"lap_number,omitempty"`
	Message      *string `json:"message,omitempty"`
	RacingNumber *int    `json:"racing_number,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	Sector       *int    `json:"sector,omitempty"`
}

type Session struct {
	SessionKey  int    `json:"session_key"`
	SessionName string `json:"session_name"`
	DateStart   string `json:"date_start"`
	DateEnd     string `json:"date_end"`
	GmtOffset   string `json:"gmt_offset"`
	SessionType string `json:"session_type"`
	MeetingKey  int    `json:"meeting_key"`
}

type Subscription struct {
}
