// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meeting struct {
	MeetingName         string `json:"meeting_name"`
	MeetingOfficialName string `json:"meeting_official_name"`
	Location            string `json:"location"`
	CountryKey          int    `json:"country_key"`
	CountryCode         string `json:"country_code"`
	CountryName         string `json:"country_name"`
	CircuitKey          int    `json:"circuit_key"`
	CircuitShortName    string `json:"circuit_short_name"`
	DateStart           string `json:"date_start"`
	GmtOffset           string `json:"gmt_offset"`
	MeetingKey          int    `json:"meeting_key"`
	Year                int    `json:"year"`
}

type Query struct {
}

type Session struct {
	SessionKey       int    `json:"session_key"`
	SessionName      string `json:"session_name"`
	DateStart        string `json:"date_start"`
	DateEnd          string `json:"date_end"`
	GmtOffset        string `json:"gmt_offset"`
	SessionType      string `json:"session_type"`
	MeetingKey       int    `json:"meeting_key"`
	Location         string `json:"location"`
	CountryKey       int    `json:"country_key"`
	CountryCode      string `json:"country_code"`
	CountryName      string `json:"country_name"`
	CircuitKey       int    `json:"circuit_key"`
	CircuitShortName string `json:"circuit_short_name"`
	Year             int    `json:"year"`
}
