# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Run tests
        run : go test -v ./...
      - name: Build
        run: go build -v ./...
      - name: Test AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: aws sts get-caller-identity
      - name: Login to DCR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_DEFAULT_REGION }}
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 796092239933.dkr.ecr.eu-west-2.amazonaws.com
      - name: Build Docker image
        run: docker build -t f1telemetry .
      - name: Tag Docker image
        run: docker tag f1telemetry:latest 796092239933.dkr.ecr.eu-west-2.amazonaws.com/f1telemetry:latest
      - name: Push Docker image
        run: docker push 796092239933.dkr.ecr.eu-west-2.amazonaws.com/f1telemetry:latest